[tool.poetry]
name = "pynit"
version = "0.1.0"
description = "A Flask-based web project for PyNit."
authors = ["Josué Santos Rocha <your-email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.2.5"
sqlalchemy = "^2.0"
requests = "^2.31.0"
gunicorn = "^21.2.0"
jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"
black = "^24.2.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
